#! /bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "AmonRaNet: install config files and related tools"
    echo "           sudo will be requested!"
    exit
fi

source $DIR/../scripts/config.sh

validate_missing_init() {
    missing=
}

validate_missing_apply() {
    if [ ! -z "$missing" ]; then
        msg_dialog "Missing generally: $missing"
        exit 1
    fi
}

copy_config() {
    CONFIG=$1
    sudo rm -vfR ~/.config/$CONFIG/*
    cp -vR $DIR/$CONFIG ~/.config/
}

echo_install "validate"
validate_missing_init
if ! test_command "ls /usr/share/fonts/opentype/font-awesome"; then
    missing="$missing font-awesome"
fi
if ! test_command "ls ~/.local/share/fonts/*Powerline*"; then
    missing="$missing font-powerline"
fi
validate_missing_apply
mark_done

echo_install "install basic-tools"
sudo cp -vR $DIR/bin/detach /usr/bin
sudo cp -vR $DIR/bin/resize-images /usr/bin
mark_done

if app_exists "i3"; then
    echo_install "i3 config"
    validate_missing_init
#    if ! test_command "i3 --version | grep gaps"; then
#        missing="$missing i3-gaps"
#    fi
    if ! test_command "ls /usr/share/notify-osd"; then
        missing="$missing notify-osd"
    fi
    dependencies=("dmenu" \
                  "i3" \
                  "i3lock" \
                  "i3status" \
                  "i3blocks" \
                  "rofi" \
                  "yad" \
                  "kbdd" \
                  "gnome-session" \
                  "xautolock" \
                  "compton" \
                  "rhythmbox-client" \
                  "xrandr" \
                  "arandr" \
                  "scrot")
    for i in ${dependencies[@]}
    do
       if ! app_exists "$i"; then
           missing="$missing $i"
       fi
    done
    validate_missing_apply

    git submodule init
    echo_task "i3 submodules"
    git submodule update

    echo_task "i3 custom scripts"
    sudo rm -vfR /usr/bin/i3-custom-*
    sudo cp -vR $DIR/bin/i3-custom-* /usr/bin

    echo_task "i3 config"
    copy_config i3

    echo_task "i3blocks config"
    copy_config i3blocks
    (cd ~/.config/i3blocks/scripts/bandwidth2 ; make)

    echo_task "i3 related python modules"
    sudo bash -c "pip3 install setuptools"
    sudo bash -c "pip3 install i3ipc"
    sudo bash -c "pip3 install fontawesome"

    echo_task "compton config"
    copy_config compton

    mark_done
else
    mark_skipped
fi

if app_exists "terminator"; then
    echo_install "terminator config"
    copy_config terminator
    mark_done
else
    mark_skipped
fi

if app_exists "gnome-terminal"; then
    echo_install "gnome-terminal config"
    dconf reset -f /org/gnome/terminal/
    dconf load /org/gnome/terminal/ < $DIR/gnome-terminal/settings_dump.txt
    mark_done
else
    mark_skipped
fi

if app_exists "variety"; then
    echo_install "variety config"
    copy_config variety
    mark_done
else
    mark_skipped
fi

if app_exists "fish"; then
    echo_install "prepare fish config"
    source-auto script fish _init_ "# fish general params
set fish_greeting
set fish_color_autosuggestion D0D0D0
set fish_color_normal normal
set fish_color_command green --bold
set fish_color_quote yellow
set fish_color_redirection magenta
set fish_color_end cyan
set fish_color_error red --bold
set fish_color_param white --bold
set fish_color_comment brgrey
set fish_color_match black --background=D0D0D0
set fish_color_search_match --background=D0D0D0
set fish_color_operator grey
set fish_color_escape brcyan

set fish_pager_color_prefix brred
set fish_pager_color_completion normal
set fish_pager_color_description brgrey
set fish_pager_color_progress magenta"
    mark_done
else
    mark_skipped
fi

if app_exists "git"; then
    echo_install "git config"
    git config --global alias.graph "log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(auto)%d%C(reset)'"
    git config --global alias.permission-reset '!git diff -p -R --no-ext-diff --no-color | grep -E "^(diff|(old|new) mode)" --color=never | git apply'
    git config --global core.excludesfile '~/.gitignore'
    git config --global credential.helper cache
    git config --global credential.helper 'cache --timeout=600'
    touch ~/.gitignore
    mark_done
else
    mark_skipped
fi
