#! /bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo "AmonRaNet: install config files and related tools"
    echo "           sudo will be requested!"
    exit
fi

source $DIR/../scripts/config.sh

validate_missing_init() {
    missing=
}
validate_missing_apply() {
    if [ ! -z "$missing" ]; then
        msg_dialog "Missing generally: $missing"
        exit 1
    fi
}

echo_install "validate"
validate_missing_init
if ! test_command "ls /usr/share/fonts/opentype/font-awesome"; then
    missing="$missing font-awesome"
fi
if ! test_command "ls ~/.local/share/fonts/*Powerline*"; then
    missing="$missing font-powerline"
fi
validate_missing_apply

echo_install "install basic tools"
sudo cp -vR $DIR/bin/detach /usr/bin
sudo cp -vR $DIR/bin/resize-images /usr/bin

if app_exists "i3"; then
    validate_missing_init
    if ! test_command "i3 --version | grep gaps"; then
        missing="$missing i3-gaps"
    fi
    dependencies=("dmenu" \
                  "i3lock" \
                  "i3status" \
                  "i3blocks" \
                  "rofi" \
                  "yad" \
                  "kbdd" \
                  "gnome-session" \
                  "xautolock" \
                  "compton" \
                  "rhythmbox-client" \
                  "xrandr" \
                  "arandr" \
                  "scrot")
    for i in ${dependencies[@]}
    do
       if ! app_exists "$i"; then
           missing="$missing $i"
       fi
    done
    validate_missing_apply

    echo_install "submodules"
    git submodule init
    git submodule update

    echo_install "i3 custom scripts"
    sudo rm -vfR /usr/bin/i3-custom-*
    sudo cp -vR $DIR/bin/i3-custom-* /usr/bin

    echo_install "i3 config"
    sudo rm -vfR ~/.config/i3/*
    cp -vR $DIR/i3 ~/.config/

    echo_install "i3blocks config"
    sudo rm -vfR ~/.config/i3blocks/*
    cp -vR $DIR/i3blocks ~/.config/
    pushd .
    cd ~/.config/i3blocks/scripts/bandwidth2
    make
    popd

    echo_install "i3 related python modules"
    sudo bash -c "pip3 install i3ipc"
    sudo bash -c "pip3 install fontawesome"

    echo_install "compton config"
    sudo rm -vfR ~/.config/compton/*
    cp -vR $DIR/compton ~/.config/
else
    echo "${RED}i3 is skipped!${NORMAL}"
fi

if app_exists "terminator"; then
    echo_install "copy terminator config"
    sudo rm -vfR ~/.config/terminator/*
    cp -vR $DIR/terminator ~/.config/
else
    echo "${RED}terminator is skipped!${NORMAL}"
fi

if app_exists "fish"; then
    echo_install "prepare fish config"
    source-auto script fish _init_ "# fish general params
set fish_greeting
set fish_color_autosuggestion D0D0D0
set fish_color_normal normal
set fish_color_command green --bold
set fish_color_quote yellow
set fish_color_redirection magenta
set fish_color_end cyan
set fish_color_error red
set fish_color_param white --bold
set fish_color_comment brgrey
set fish_color_match black --background=D0D0D0
set fish_color_search_match --background=D0D0D0
set fish_color_operator grey
set fish_color_escape brcyan

set fish_pager_color_prefix brred
set fish_pager_color_completion normal
set fish_pager_color_description brgrey
set fish_pager_color_progress magenta"
else
    echo "${RED}fish is skipped!${NORMAL}"
fi
